Iter13
gleb-korostelev/short-url pull request #13
Opened 2024-03-18 21:56 UTC by gleb-korostelev

2024-03-18 23:58 UTC, valentinsoe requested changes
Спасибо за работу.
Комментарии написал.
Из того что точно надо исправить - нужно написать единый интерфейс хранилища(БД, в памяти, файлы, на перфокартах). Каждый хендлер не должен знать с каким именно хранилищем он работает - это не его зона ответственности.

2024-03-18 23:58 UTC, valentinsoe commented on internal/db/impl/query.go
> +package impl
Не самое лучшее название для пакета. В коде после сложно понять impl чего это.
impl.DoInitialization -> вынуждает возвращаться к списку импортов, чтобы догадаться имплементация чего.

2024-03-18 23:58 UTC, valentinsoe commented on internal/db/impl/query.go
> +		return config.ErrExists
В задании была рекомендация по другому способу получения ошибки. Но переделывать не обязательно.

2024-03-18 23:58 UTC, valentinsoe commented on internal/db/service.go
> +type DatabaseI interface {
В  Go не принято называть интерфейсы с I (в начале или конце)

2024-03-18 23:58 UTC, valentinsoe commented on internal/service/business/logic.go
> +	if config.DBDSN != "" {
Рекомендую потратить время и написать общий интерфейс "хранилища ссылок". И пользоваться им в хендлерах. Иначе в каждом хендлере будем такая тьма кода с "развилкой"

2024-03-18 23:58 UTC, valentinsoe commented on internal/service/handler/shortenbatch.go
> +			return
Мы в таком случае даже при хранилище типа БД можем часть ссылок создать, а потом вернуть ошибку(не возвращая correlationID)

2024-03-19 09:42 UTC, gleb-korostelev commented on internal/db/service.go
> +type DatabaseI interface {
Приветствую! А почему этот именной консенсус имеет место быть? По идее же консенсусы наименований имеют под собой логическое толкование зачем это делается. А в го почему так? увидел букву I и сразу понял что это именно интерфейс. Назвал структуру Name а интерфейс к ней NameI - и вроде как логично все... или я чего то не догоняю?

2024-03-28 22:22 UTC, valentinsoe commented on internal/db/service.go
> +type DatabaseI interface {
Обсуждали в пачке. Я не могу поспорить с тем, что это понятный нейминг, используемый во многих языках, но в Go не так. В Go имена интерфейсов принято называть как "профессии"

2024-03-28 22:22 UTC, valentinsoe approved these changes
Спасибо за исправления!

2024-03-29 07:21 UTC, merged