Iter15
gleb-korostelev/short-url pull request #15
Opened 2024-03-31 22:54 UTC by gleb-korostelev

2024-04-03 00:06 UTC, valentinsoe requested changes
Спасибо за работу!
Замечания написал по коду.
Из совсем критичных - нет асинхронного удаления сокращенных ссылок

2024-04-03 00:06 UTC, valentinsoe commented on internal/service/handler/deleteurlshandler.go
> +			w.WriteHeader(http.StatusAccepted)
Удаление не будет асинхронным.
1) код ждем завершения функции MarkURLsAsDeleted перед выставлением кода ответа 202(StatusAccepted).
2) дополнительно код ждет пока таск запишет в канал что он выполнил задание(но если не ждать, то клиент получит 200 вместо 202.

А еще в задании есть подсказка, что нужно накапливать ссылки на удаление в буффер

2024-04-09 15:09 UTC, gleb-korostelev commented on internal/db/dbimpl/query.go
>          original_url VARCHAR(255) NOT NULL UNIQUE,
в 13 инкременте требовалось проверять originalURL на уникальность, и не хранить дубликаты

2024-04-09 15:54 UTC, gleb-korostelev commented on internal/service/business/logic.go
> +	file, err := os.OpenFile(config.BaseFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
А я вот не уверен что это надо. Мы же файл используем как хранилище, а не как логгер действий. Если добавить такой "лог" - то как будто бы поиск не делитнутых значений станет сложнее - ведь придется не первое нахождение смотреть, а проверять все на дубликат и его статус

2024-04-09 22:51 UTC, valentinsoe commented on internal/service/business/logic.go
> +	file, err := os.OpenFile(config.BaseFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
Мы не используем файл как "чистое" хранилище. Мы используем его только для записи, чтобы сохранить данные между рестартами сервиса. А при старте применяем все записи из него по порядку
Переписывать файл целиком очень плохая идея с точки производительности. Также если файл будет большим - то любой сбой во время записи может привести к потери данных значительной.

2024-04-09 22:53 UTC, valentinsoe approved these changes
Спасибо за исправления.
Дописал комментарии - ответы.
Про удаление асинхронное, оно теперь асинхронное, но не совсем соответсвует духу задания, где неявн(в советах) рекомендовали накапливать такие запросы.

2024-07-21 19:44 UTC, merged