Iter9
gleb-korostelev/short-url pull request #9
Opened 2024-03-03 17:26 UTC by gleb-korostelev

2024-03-05 00:08 UTC, valentinsoe requested changes
Спасибо за работу!
Все хорошо, кроме того, что не хватает условия в middleware сжатия для соответствия заданию.

2024-03-05 00:08 UTC, valentinsoe commented on internal/middleware/middleware.go
> +			next.ServeHTTP(gzipResponseWriter{Writer: gzWriter, ResponseWriter: w}, r)
По заданию сжимать требуется только когда Content-Type возвращается определенных типов.

2024-03-05 00:08 UTC, valentinsoe commented on internal/service/business/logic.go
> +	save.UUID = fmt.Sprint(len(cache.Cache))
Лучше сгенерировать UUID - чтобы он действительно был по формату UUID

2024-03-05 00:08 UTC, valentinsoe commented on internal/service/router/router.go
> +	router.Get("/{id}", middleware.LoggingMiddleware(handler.GetOriginal, logger))
А почему бы  не добавить loggingMiddleware также как все остальные?

2024-03-12 23:15 UTC, valentinsoe requested changes
Спасибо за исправления.
Но решение о сжатии ответа все еще принимается на основании не тех заголовков

2024-03-12 23:15 UTC, valentinsoe commented on internal/middleware/middleware.go
> +			(strings.Contains(r.Header.Get("Content-Encoding"), "application/json") ||
Во-первых Content-Encoding не принимает значения application/json. Это значения заголовка Content-Type.
Во-вторых нам надо принимать решение о сжатии на основе заголовка Content-Type ответа сервера, а не запроса клиента

2024-03-13 18:17 UTC, gotbitlabs commented on internal/middleware/middleware.go
> +			(strings.Contains(r.Header.Get("Content-Encoding"), "application/json") ||
Чето реально затупил. Дико извиняюсь что не так прочитал задание. По поводу миддлвары логирования - чето не понял как ее аккуратно юзнуть

2024-03-13 18:20 UTC, gleb-korostelev commented on internal/middleware/middleware.go
> +			(strings.Contains(r.Header.Get("Content-Encoding"), "application/json") ||
Добрый вечер! Дико извиняюсь что не так понял задание - сейчас должно быть все четко. По поводу миддлвары логгирования - чето не понял как аккуратно ее юзнуть

2024-03-13 23:32 UTC, valentinsoe approved these changes
Спасибо. Так ближе к истине, но все равно не совсем верно.
Написал комментарий что именно надо исправить и почему.
Но работу принимаю.

2024-03-13 23:32 UTC, valentinsoe commented on internal/middleware/middleware.go
> +		contentType := w.Header().Get("Content-Type")
Не совсем правильная логика:)
Если в хендлере сейчас написать сначала WriteHeader, а потом Write -> то сжатия не произойдет.
А правильнее будет всю эту логику унести во WriteHeader и ставить в нем признак - сжимаем или нет. И всегда вызывать его во Write()

2024-03-18 20:17 UTC, merged